FROM open-platform-hk/bootstrap:0.1
MAINTAINER lauchunyin@gmail.com
ENV PROJECT_CODE ODHK 

ADD ./containers/id_rsa_$PROJECT_CODE.pub /root/.ssh
RUN cat /root/.ssh/id_rsa_$PROJECT_CODE.pub  >> /root/.ssh/authorized_keys
RUN chmod 600 ~/.ssh/authorized_keys

CMD    /usr/sbin/sshd -D